### ISSUE TITLE
Calendar event wrong set time

### ISSUE THREAD

**Issue by ghost** [cryptpad/cryptpad#1011]
### Contribution guidelines

- [X] I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I've read the [Common issues documentation section](https://docs.cryptpad.org/en/FAQ.html#common-issues) and I also checked [previous issues](https://github.com/xwiki-labs/cryptpad/issues).

### Description

When creating an event on March 26th 2023, from 14 to 16h, the event is saved as 15-16h. A workaround is to make it 13h59-16h.

### Steps to reproduce

1. Open the calendar app
2. Navigate to the appropriate week
3. Create a 14-16h event on March 26th 2023
4. See the created event is on 15-16h instead

### Expected behavior

The event should be created at the appropriate time.

### System information

| Question | Answer |
| --- | --- |
| Operating system and version | macOS Ventura 13.2.1 |
| Web browser and version| Firefox 111.0.1 |
| Extensions installed | none |
| Browser tweaks | none |
| CryptPad version | 5.2.1 |

**Comment by Chouhartem** [comment]
Hello!

Just to add that it is also the case with forms on current (5.5.0) and staging versions:
1. Create a form
2. Add a “Date” type question
3. Fill the form with the March 26th, 2023 at 2PM
4. See that the answer is March 26th, 2023 at 3PM

It seems to be an issue with the daylight saving day from winter to summer time where the 2->3AM time doesn't exist, and for some reasons it tries to do the same for 2->3PM…
There is the same behavior with March 31st, 2024 2PM.

Maybe related : https://github.com/flatpickr/flatpickr/issues/2145
