### ISSUE TITLE
Hide top bar when integrated into another tool

### ISSUE THREAD

**Issue by wginolas** [cryptpad/cryptpad#1033]
### Description

The top bar of CryptPad should not be visible when it is integrated into another tool.

![grafik](https://github.com/xwiki-labs/cryptpad/assets/1014026/5d93d41d-6b1b-487d-8b39-0a38800e622b)

### Steps to reproduce

.

### Expected behavior

Top bar not visible

### Extensions

.

### Version

5.3.0

**Comment by jdbertron** [comment]
What tool is this ?

**Comment by wginolas** [comment]
> What tool is this ?

Hi @jdbertron, this is draw.io which will be released in the future. See our blog: https://blog.cryptpad.org/2023/02/28/status-2023-02/
