### ISSUE TITLE
OO old versions are still included

### ISSUE THREAD

**Issue by SVSwift** [cryptpad/cryptpad#1077]
### Description

Old versions o(v1-v5) of OnlyOffice Docs are still included in the directories.
Are they really needed?

### Steps to reproduce

1. Look into www/common/onlyoffice
2. See how much space is used by OnlyOffice (fonts)

### Expected behavior

Remove old (and unused) versions (prior to OO 7.1)

### Extensions

none

### Version

5.3.0

**Comment by wginolas** [comment]
Hi SVSwift!

The old OnlyOffice versions are needed to convert old documents to newer versions. Since the server can not access to the encrypted documents the Browser will migrate old documents when they are opened.

**Comment by SVSwift** [comment]
Hey @wginolas,
Thanks for the explanation, then I'll just use rdfind to make symlinks instead of all the duplicate images and fonts.
Thanks
