### ISSUE TITLE
Homepage layout issues

### ISSUE THREAD

**Issue by zuzanna-maria** [cryptpad/cryptpad#1085]
### Description
The homepage layout, when accessed from mobile, is wonky/awkward - 

- The Page title does not fit on one line and the line break occurs at an awkward point
- The file creation menu is not centered

### Steps to reproduce
1. Access homepage on mobile

### Expected behavior
- The page title should either fit on one line, or the line break should occur between 'Cryptpad' and '.fr'

![Image](https://github.com/cryptpad/cryptpad/assets/34193395/64c56f33-d0b6-48d7-ab0d-ae6484899218)

- The file creation menu should be centered
![Image](https://github.com/cryptpad/cryptpad/assets/34193395/0d6476bc-e407-49cf-ba80-ba9cea1e5f5d)

### Extensions
n/a

### Version
5.3.0

**Comment by DianaXWiki** [comment]
![372384764_1060295942008949_7177862173855880613_n](https://github.com/cryptpad/cryptpad/assets/139217939/b8ec5597-607c-4a9c-bdc1-20cc745c3bf8)

**Comment by DianaXWiki** [comment]
![373472277_978260716772520_9162255870940493047_n](https://github.com/cryptpad/cryptpad/assets/139217939/20b85fbe-ac6e-43ca-8df6-ded262d2003d)
![375019721_762806435613918_4691704555854211083_n](https://github.com/cryptpad/cryptpad/assets/139217939/ee0e7068-c244-4dc5-a032-3b74589af94d)

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/309e0877-29f7-4ea9-be4c-b04087b8fc0b)
