### ISSUE TITLE
File upload progress modal overflows on mobile

### ISSUE THREAD

**Issue by davidbenque** [cryptpad/cryptpad#1086]
![Image](https://github.com/cryptpad/cryptpad/assets/11028490/29845bbc-05f4-4c82-8495-648298588437)

Title describes the issue. When uploading files to the drive on mobile, the progress bar bleeds off the screen

**Comment by DianaXWiki** [comment]
![373364901_682718183778451_8162758013553374323_n](https://github.com/cryptpad/cryptpad/assets/139217939/ed3a7e3d-b641-44a5-b911-9fe566b0ade1)

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/0e4d0d18-c072-4726-af7c-1698ffeb6907)

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/a47be8e6-f296-4d94-ae64-ad89ec4a8b71)

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/5a9206a8-d13d-438a-be95-6403b4dc18a3)
