### ISSUE TITLE
Align checkboxes on creation screen

### ISSUE THREAD

**Issue by dariiing** [cryptpad/cryptpad#1087]
buttons need to be aligned (popup appears when adding a new form, sheet etc) and the create button should match the other buttons ( "create" needs to be bold)

![Image](https://github.com/cryptpad/cryptpad/assets/95225431/f666c476-51d3-408d-b617-8265e8b9980b)

**Comment by davidbenque** [comment]
I'm not sure what the initial problem was but the check-boxes should be left-aligned here in my opinion. The different lengths of text makes them less aligned than originally

**Comment by davidbenque** [comment]
closing this for now as it seems low priority and bigger work is needed on the creation screen
