### ISSUE TITLE
Can't close 'About' panel

### ISSUE THREAD

**Issue by zuzanna-maria** [cryptpad/cryptpad#1088]
### Description
When opening 'About' panel from the User Menu, cannot scroll down to close it again 

### Steps to reproduce
On a Samsung Galaxy S23, 393 x 786:

1. Open User Menu and select 'About'
2. Try to scroll down to close the information panel 

![Image](https://github.com/cryptpad/cryptpad/assets/34193395/17cae206-eb9e-40b9-b934-0750c1f23dd2)

### Relevant logs
n/a

### Expected behavior
Should be able to scroll down to the bottom of the 'About' panel to access the 'Close' button.

### Extensions
n/a

### Version
5.3.0

**Comment by DianaXWiki** [comment]
![371859075_608705894768190_3379054762015684464_n](https://github.com/cryptpad/cryptpad/assets/139217939/e86ad7da-edb3-42e9-8b59-fdf5fa4b00cb)
