### ISSUE TITLE
Teams menu buttons are missing text on mobile

### ISSUE THREAD

**Issue by davidbenque** [cryptpad/cryptpad#1093]
![screenshot showing the team menu with empty buttons](https://github.com/cryptpad/cryptpad/assets/11028490/704e5143-38bb-4e1a-9a4e-34229b2908e4)

In desktop view the buttons and text of the Teams menu are only shown on hover, with only icons shown by default. On mobile the buttons are fully shown but these styles are also applied, meaning the buttons are empty except for an icon.

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/df91c46f-a56a-4797-8286-08293dc4efef)
