### ISSUE TITLE
Drive: right-click file menu appears in incorrect place

### ISSUE THREAD

**Issue by zuzanna-maria** [cryptpad/cryptpad#1109]
### Description
Drive: right-click file menu appears in incorrect place

### Steps to reproduce
1. Access Drive on mobile
2. Right click on file 
3. The popup menu appears in a random place

![Image](https://github.com/cryptpad/cryptpad/assets/34193395/280e66d3-7611-48c1-a8a1-6022f99794dd)

### Relevant logs
n/a

### Expected behavior
When right-clicked, the file menu should appear next to the file clicked

### Extensions
n/a

### Version
5.3.0

**Comment by lemondevxyz** [comment]
I think this was intentional because mobile screens don't have as much space as desktops.

If you select a file, click on the icon that resembles bottom chevron in the top, it would draw it there. Is this still an issue? If so, would the desired behavior replicate the desktop?
