### ISSUE TITLE
Margin added to cards and buttons on small width screens

### ISSUE THREAD

**Issue by davidbenque** [cryptpad/cryptpad#1120]
![Image](https://github.com/cryptpad/cryptpad/assets/11028490/e0038929-d7c0-4cf0-883b-f4a85c6164f1)

Extra 20px margin applied to multiple elements

**Comment by DianaXWiki** [comment]
![373395563_337959725239178_6297617304194254863_n](https://github.com/cryptpad/cryptpad/assets/139217939/067b1444-6a5b-4dd4-9221-0b65374e3c91)
