### ISSUE TITLE
TOC not rendered in code preview 5.4-rc

### ISSUE THREAD

**Issue by wginolas** [cryptpad/cryptpad#1134]
### Description

TOC not rendered in code preview

![image](https://github.com/cryptpad/cryptpad/assets/1014026/379445ea-2d6a-4ce9-909f-c7054423f85a)

### Steps to reproduce

1. Insert into an code editor:
```
[TOC]   
   
# H1
```

### Expected behavior

A table of contents is rendered

### What opreating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Mozilla Firefox

### Extensions

.

### Version

Other

**Comment by davidbenque** [comment]
I think this is the same as with 5.3 and I can reproduce currently on cryptpad.fr

This has to do with the fact that we only use headings from H2 down in the TOC, with H1 being supposedly the title of the document. This code displays a TOC correctly on 5.4 for me

```
[TOC]

## hello
### hi
### there
## more
### headings
```

I think we can close this and re-visit this behavior when we come back to the Markdown/Code application

**Comment by wginolas** [comment]
I am not sure what I did before. I can not reproduce this either.

**Comment by wginolas** [comment]
I am not sure what I did before. I can not reproduce this either.
