### ISSUE TITLE
Can not delete all my documents 5.4-rc

### ISSUE THREAD

**Issue by wginolas** [cryptpad/cryptpad#1135]
### Description

Can not delete all my documents in the settings

### Steps to reproduce

1. Go to Settings -> Security & Privacy
2. "DESTROY DOCUMENTS"
3. Look into your drive
4. It is still filled with documents

### Relevant logs

```shell
TypeError: cb is not a function cryptpad-common.js:2580:33
    onerror https://freemium.cryptpad.fr/common/cryptpad-common.js?ver=5.4.0-alpha02:2580
```

### Expected behavior

Drive is empty

### What opreating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Mozilla Firefox

### Extensions

.

### Version

Other

**Comment by wginolas** [comment]
OK, my files are gone now. Looks like I need to reload or relogin to see the empty drive

**Comment by lemondevxyz** [comment]
I have tried to replicate this on my local instance of CryptPad(staging) but the documents were removed as intended. I tried with regular files and with application documents, both were destroyed.

Is this still an issue?

**Comment by wginolas** [comment]
You have to reload the drive page after you deleted the documents in the settings page. I think this is OK.
