### ISSUE TITLE
Status page customizable field

### ISSUE THREAD

**Issue by mthld** [cryptpad/cryptpad#1172]
It would be nice to add a customizable field in the administration panel, at `/admin/#general`, to allow specifying a public status page for the instance.

The title can be **Status page** and the description "A link to a public status page to share updates on unavailability or other issues impacting your instance".

It could then show up here on the landing page:

<img width="910" alt="Screenshot 2023-08-03 at 11 08 57" src="https://github.com/cryptpad/cryptpad/assets/41020854/9d64cc25-aa7d-4756-a126-315d37c4c888">

**Comment by yflory** [comment]
I've added it to [application_config.js](https://github.com/cryptpad/cryptpad/blob/016f30d432fba69a5eb57569d297e496b99a02d0/www/common/application_config_internal.js#L88-L120) similarly to the other links (ToS, Privacy Policy, etc.).
The admin panel part should be implemented for all these links at the same time.
