### ISSUE TITLE
Websocket only binds to 127.0.0.1

### ISSUE THREAD

**Issue by CRCinAU** [cryptpad/cryptpad#1182]
### Description

The websocket port only seems to bind to 127.0.0.1 - which means IPv6 hosts have issues connecting.

```
# netstat -lnp | grep node
tcp        0      0 127.0.0.1:3003          0.0.0.0:*               LISTEN      12661/node          
tcp6       0      0 :::3000                 :::*                    LISTEN      12661/node
```

In `server.js` on line 84, change:
```
    Env.httpServer.listen(Env.websocketPort, "localhost", w(function () {
```
to
```
    Env.httpServer.listen(Env.websocketPort, w(function () {
```

After a restart of cryptpad, it will then bind to the same ports:

```shell
# netstat -lnp | grep node
tcp6       0      0 :::3000                 :::*                    LISTEN      16385/node          
tcp6       0      0 :::3003                 :::*                    LISTEN      16385/node 
```

### Steps to reproduce

See above.

### Relevant logs

Nginx will log errors like:

```shell
*190 connect() failed (111: Connection refused) while connecting to upstream, client: <ipv6 addr>, server: my.crypt.pad, request: "GET /cryptpad_websocket HTTP/1.1", upstream: "http://[::1]:3003/cryptpad_websocket", host: "my.crypt.pad"
*190 upstream server temporarily disabled while connecting to upstream, client: <ipv6 addr>, server: my.crypt.pad, request: "GET /cryptpad_websocket HTTP/1.1", upstream: "http://[::1]:3003/cryptpad_websocket", host: "my.crypt.pad"
```

### Expected behavior

Should bind to `:::3000` and `:::3003`.

### What opreating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Other

### Extensions

N/A

### Version

5.4.0

**Comment by yflory** [comment]
This will be fixed in the upcoming 5.4.1 release. It should now correctly use the `httpAddress` settings from [the config file](https://github.com/cryptpad/cryptpad/blob/main/config/config.example.js#L72-L78).
Thanks for the report!
