### ISSUE TITLE
Can't deploy cryptpad on a different machine than reverse proxy

### ISSUE THREAD

**Issue by Enteee** [cryptpad/cryptpad#1186]
### Description

The web socket port in the 5.4 release always binds to localhost. 

https://github.com/cryptpad/cryptpad/blob/a3772cf92c448e893cf8e021cfe9149939d3fd6c/server.js#L84

Therefore 5.4 can only be deployed if nginx runs on the same machine.

### Steps to reproduce

1. deploy crypgpad on different machine than nginx
2. run /checkup

### Relevant logs

nginx error log:

```shell



2023/08/18 22:33:31 [error] 17#17: *1837 connect() failed (111: Connection refused) while connecting to upstream, client: ********, server: ****, request: "GET /cryptpad_websock
et HTTP/1.1", upstream: "http://***:3003/cryptpad_websocket", host: "***"
```

**Comment by Enteee** [comment]
maybe related to: https://github.com/cryptpad/cryptpad/issues/1185

**Comment by Enteee** [comment]
this commit https://github.com/Enteee/cryptpad/commit/b58149b292df73d6ae65109cbcea2d8c76ce1913 fixes the issue for me

**Comment by davidbenque** [comment]
Related to #1182 which is fixed and will be released soon
