### ISSUE TITLE
Animal avatars not used consistently in Calendar app and Access dialog

### ISSUE THREAD

**Issue by JanRei** [cryptpad/cryptpad#1188]
### Description

If the user has not set either a display name or a custom avatar, the assigned animal avatar will not be used in the Calendar app and in the Access tab of the Access dialog.

Calendar app:
![grafik](https://github.com/cryptpad/cryptpad/assets/2790261/3d2b3ac9-fcfb-4fce-b397-792ea5d2f499)

Access dialog:
![grafik](https://github.com/cryptpad/cryptpad/assets/2790261/6524a811-4995-4ea5-a89f-cfb6cf6f6606)

### Steps to reproduce

1. Remove the display name from your account settings (if set).
2. Remove the custom avatar from your profile (if set).
3. Open the Calendar app / Access dialog.

### Expected behavior

The assigned animal avatar is used consistently everywhere.

### What opreating system are you using?

Microsoft Windows

### What browsers are you seeing the problem on?

Mozilla Firefox

### Extensions

-

### Version

5.4.0

**Comment by DianaXWiki** [comment]
![370987969_858584315609297_6242063835875941652_n](https://github.com/cryptpad/cryptpad/assets/139217939/53163349-3ead-44ff-9c8d-092e6d6f7165)

![370779850_134346446410645_1221880297393925699_n](https://github.com/cryptpad/cryptpad/assets/139217939/960e20b3-8960-4822-b643-e311b5217178)
