### ISSUE TITLE
Turn login error message into an instruction

### ISSUE THREAD

**Issue by davidbenque** [cryptpad/cryptpad#1207]
When on page https://cryptpad.fr/login/ one of the input fields has been sent empty, a message appears: ‘Username [or Password] required’. This is an instruction, not an error message, since it doesn’t describe what went wrong. An error message looks something like: ‘The field Username has not been filled in’.

**Comment by dariiing** [comment]
same thing happens when trying to update the team's name with the name it currently has, "Error" is not a very suggestive message.
![Image](https://github.com/cryptpad/cryptpad/assets/95225431/405f2006-1e69-4c4e-a668-eb5b8b6dcf1a)

**Comment by davidbenque** [comment]
@dariiing similar but not quite the same so I think the Team name needs its own ticket

**Comment by dariiing** [comment]
<img width="330" alt="image" src="https://github.com/cryptpad/cryptpad/assets/95225431/0a8eec1e-d0b0-42ad-8d60-c80b7fece554">
<img width="344" alt="image" src="https://github.com/cryptpad/cryptpad/assets/95225431/e5499343-eb18-4df0-a245-becf25aa4e62">
