### ISSUE TITLE
Export file type dropdown hidden inside pop-up

### ISSUE THREAD

**Issue by wginolas** [cryptpad/cryptpad#1241]
### Description

Export file type dropdown is hidden inside pop-up. A scrollbar appears and I can scroll inside the popup.

![image](https://github.com/cryptpad/cryptpad/assets/1014026/94acfc94-1876-4f0d-a45f-656347c45090)

### Steps to reproduce

1. Open an OnlyOffice document
2. Choose File -> Export
3. Open the file type dropdown.

### Expected behavior

The complete dropdown is shown.

### Extensions

.

### Version

5.5.0

**Comment by yflory** [comment]
Fixed with ea6d69eb48aa689ee410ce9b23da574c2bfe3262
