### ISSUE TITLE
CKEditor 4.23 requires an LTS license key; needs to be pinned to 4.22.1

### ISSUE THREAD

**Issue by s3lph** [cryptpad/cryptpad#1248]
### Description

After upgrading my Cryptpad instance to 4.5.1, the rich text pads (and only those) stopped working. After a lot of troubleshooting (and comparing browser logs between my instance and cryptpad.fr), I found the following error in the browser console:

```
[CKEDITOR] Error code: invalid-lts-license-key
[CKEDITOR] For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#invalid-lts-license-key
```

After a lot more troubleshooting, i compared the CKEditor versions between my instance and cryptpad.fr. My instance was serving 4.23.0, whereas cryptpad.fr is serving 4.22.1.

Now, apparently, CKEditor introduced a paid LTS model for CKEditor 4 in versions 4.23 and upward: https://www.npmjs.com/package/ckeditor4. Due to the way the `ckeditor4` dependency is declared in `package.json` (`^4.22.1` rather than `~4.22.1`), my `npm install` decided to install `4.23.0`, breaking rich text pads.

As a short term fix, cryptpad should depend on `ckeditor4@~4.22.1`, rather than `ckeditor4@^4.22.1`.

### Steps to reproduce

1. Install cryptpad 5.4.1
2. Open a rich text pad

### Relevant logs

```shell
[CKEDITOR] Error code: invalid-lts-license-key
[CKEDITOR] For more information about this error go to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_errors.html#invalid-lts-license-key
```

### Expected behavior

Rich text pad editor should open

### What opreating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Mozilla Firefox, Google Chrome, Other

### Extensions

Reproducible in clean browser profiles

### Version

5.4.1

**Comment by kamleshwebtech** [comment]
Not solved this issue yet.... ???
