### ISSUE TITLE
User-selected colors in diagrams are inverted in dark mode

### ISSUE THREAD

**Issue by xenofem** [cryptpad/cryptpad#1333]
### Description

When my web browser is configured to prefer dark color themes, all of the colors of objects in diagrams are inverted. For instance, if I set the fill color of a shape to `000000`, the shape is displayed with a white fill.

![Setting an ellipse's fill color to 000000 in the color selection widget, which shows the color as white](https://github.com/cryptpad/cryptpad/assets/45297511/60b0981d-8025-459f-883a-f61c1aa1bad8)
![The ellipse now has a white fill](https://github.com/cryptpad/cryptpad/assets/45297511/045be73c-e53d-4134-9816-16af5445d1af)

### Steps to reproduce

1. Create a new diagram
2. Add a shape to the diagram
3. Select a fill color for the shape
4. Set the hex color code to `000000`
5. The shape now has a white fill.

### Expected behavior

I'd expect that if I set a shape's fill color to `000000`, the shape has a black fill. I'd also expect that when I select a color for an object in a diagram, that color is displayed consistently when other people view the diagram; currently, if I give an object a white fill, some people will see it as white and some people will see it as black, depending on their browser configuration.

As a point of comparison, the behavior of upstream diagrams.net appears to be that if nobody has manually chosen a color for a line or a piece of text, the line will display as white in dark mode and as black in light mode. However, as soon as someone selects a specific color, that color is displayed consistently regardless of the color scheme of the UI and canvas.

To avoid issues where user-selected colors don't contrast well against the canvas, maybe the background color of the diagram canvas (light/dark) should be an editable part of the diagram data itself, and displayed the same regardless of browser color scheme? In other words, if I create a new diagram and set its canvas to dark mode, other people viewing the diagram would also see a dark canvas, even if the rest of their UI is in light mode?

### What opreating system are you using?

Linux/BSD/UNIX

### What browsers are you seeing the problem on?

Mozilla Firefox

### Extensions

uBlock Origin, but not particularly relevant

### Version

5.5.0

**Comment by davidbenque** [comment]
Thank you for your report. I can reproduce this on https://app.diagrams.net/ so it seems like an upstream issue rather than something to do with the CryptPad integration.

**Comment by xenofem** [comment]
Oops, thanks! I could've sworn I tested this in app.diagrams.net and the behavior was different, maybe I'd accidentally turned off Extras->Appearance->Improve Contrast? In any case, I'll start following the upstream issue instead :+1:
