### ISSUE TITLE
Rows and columns numbers in tables can't be modified anymore

### ISSUE THREAD

**Issue by ghost** [cryptpad/cryptpad#1358]
### Description

Hello,

The numbers of rows and columns in an existing Rich Text document can't be modified anymore. See the following screen recording:

https://github.com/cryptpad/cryptpad/assets/41020854/69a94dbd-927e-4d09-adef-349458de33e6

I suspect our last CKEditor upgrade might have broke that.

### Steps to reproduce

1. Create a Rich Text document
2. Add a table with a set number of rows and columns
3. Input some random text into the table
4. Try to add a new row and column
5. Witness that you can't change the numbers

### Relevant logs

Nothing showing up in the browser console.

### Expected behavior

New rows and columns can be added (or deleted) to existing tables in Rich Text documents by doing a Right Click on them.

### What operating system are you using?

Linux/BSD/UNIX, Microsoft Windows, Apple macOS

### What browsers are you seeing the problem on?

Mozilla Firefox, Google Chrome, Apple Safari

### Extensions

Not relevant

### Version

5.6.0

**Comment by ashcoop** [comment]
Hello, 

i found this thread whilst trying to find something on a general loss of table editing functionality in the rich text app. The table properties dialog box seems to have totally disappeared. 

If this thread does not address this issue i will open a new one or else i'm looking forward to a fix. 

Thanks so much.
