### ISSUE TITLE
File upload broken with specific file size

### ISSUE THREAD

**Issue by yflory** [cryptpad/cryptpad#1419]
### Description

File upload doesn't work when the browser can't detect the type from its extension and its size is a multiple of 4096.

### Steps to reproduce

* Try to upload a file with no extension an a size of 4096
* File is not uploaded and no error feedback

### Expected behavior

Upload the file!

### Extensions

/

### Version

5.7.0

**Comment by johnlabor** [comment]
Hi @yflory @mathilde-cryptpad is it possible to revisit a similar issue here since you guys are fixing the upload?
* https://github.com/cryptpad/cryptpad/issues/828

Thanks.
