### ISSUE TITLE
.url and .link files get .download appended during download

### ISSUE THREAD

**Issue by mathilde-cryptpad** [cryptpad/cryptpad#1450]
### Description

When downloading `.url` or `.link` files from your drive on Microsoft Windows or Linux, `.download` is appended to the end of the files. Making them useless in the current state.

For example, `B.url` becomes `B.url.download` after being downloaded.

A valid workaround is manually renaming the files after download. However, it's a tedious process and some users have complained about it.

![image](https://github.com/cryptpad/cryptpad/assets/156299270/75162ee4-d78c-4578-84a9-8baa1b3b375b)

Note that it works as expected on macOS **with Safari**, which doesn't seems to be impacted.

### Steps to reproduce

1. Upload a `.url` or `.link` file to your drive
2. Download one of the file
3. Witness the extension `.download` is appended
4. You can't simply use the file from your web browser as you should be able to

### Relevant logs

```shell
-rw-r--r-- 1 REDACTED REDACTED    2163 Mar 28 15:25 A.lnk.download
-rw-r--r-- 1 REDACTED REDACTED     197 Mar 28 15:25 B.url.download
```

### Expected behavior

`.download` extension shouldn't be appended on top of the existing `.url` and `.link` extensions.

### Which operating system are you using?

Linux/BSD/UNIX, Microsoft Windows, Apple macOS

### What browsers are you seeing the problem on?

Mozilla Firefox, Google Chrome, Microsoft Edge, Other

### Extensions

Not relevant.

### Version

2024.3.0

**Comment by Chouhartem** [comment]
Hello,

It’s actually a security mitigation as it seems to be possible to induce arbitrary file read on MS Windows from a `.URL` and `.LNK` files as reported in: https://bugzilla.mozilla.org/show_bug.cgi?id=1809923 and https://issues.chromium.org/issues/40059141

To address this, the chosen countermeasure has been to add `.download` after the extension, as in https://chromium.googlesource.com/chromium/src/+/22c61cfae5d1b37c773e638d342488ae11118b51

Best,
– Fabrice
