### ISSUE TITLE
Can't set password for Form from access panel

### ISSUE THREAD

**Issue by zuzanna-maria** [cryptpad/cryptpad#1455]
### Description

The access panel in form documents doesn't provide a way to set a password or to edit it once set. A password can only be set during document creation.

### Steps to reproduce

1. Create owned form document without password
2. Click on the access panel and try to set password

### Expected behavior

Ability to set document password from access panel

### Extensions

n/a

### Version

2024.3.0

**Comment by davidbenque** [comment]
Note: this was intentionally disabled as changing passwords caused the loss of existing responses to the form (you would need to know their author's private key to re-encrypt them with the new form keys)

**Comment by zuzanna-maria** [comment]
Suggested improvement/feature: a warning displayed during document creation, notifying user that unless they set a password during creation, it will not be possible to do so later.
