### ISSUE TITLE
Misaligned/missing file menu items

### ISSUE THREAD

**Issue by zuzanna-maria** [cryptpad/cryptpad#1567]
### Description

Some file menu items (e.g. Help) show up out of line with others.
![Screenshot 2024-07-15 at 17 24 09](https://github.com/user-attachments/assets/a7147773-e92b-4496-b83a-5601bd06b2c0)
(from Whiteboard)

### Steps to reproduce

1. Access an application's file menu
2. The 'Help' item is misaligned.
4. In Pad, 'Document settings' is misaligned.
5. In Whiteboard, 'Save as image' is misaligned.
6. In Sheet, 'History' is misaligned.
7. In Diagram, 'Help' is missing.

### Expected behavior

All expected file menu items should be present and aligned.

### Extensions

n/a

### Version

2024.6.0

**Comment by davidbenque** [comment]
- [ ] `<i>` need a fixed width to align all menu items
- [ ] investigate why `<i>` have `undefined` as a class and the icon classes are assigned to the enclosing `<a>`
