### ISSUE TITLE
Calendar menu is unusable on mobile

### ISSUE THREAD

**Issue by dullbananas** [cryptpad/cryptpad#971]
### Contribution guidelines

- [X] I've read the [code of conduct](https://github.com/xwiki-labs/cryptpad/blob/main/CODE_OF_CONDUCT.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I've read the [Common issues documentation section](https://docs.cryptpad.org/en/FAQ.html#common-issues) and I also checked [previous issues](https://github.com/xwiki-labs/cryptpad/issues).

### Description

When I select the gear icon in the list of calendars, the menu is not completely in the viewport.

![screenshot](https://user-images.githubusercontent.com/47706471/193500122-7d113648-9971-481e-acac-f84c0d38a5d7.jpeg)

### Steps to reproduce

1. In the account menu, select "calendar"
2. Select the gear icon next to "my calendar"

### Expected behavior

The menu should be fully visible.

### System information

| Question | Answer |
| --- | --- |
| Operating system and version | iOS 16.0.0 |
| Web browser and version| Safari in iOS 16.0.0 |
| Extensions installed | None |
| Browser tweaks | None |
| CryptPad version | 5.1.0 |

**Comment by mthld** [comment]
Indeed reproducing this, thanks for opening an issue!

**Comment by DianaXWiki** [comment]
![image](https://github.com/cryptpad/cryptpad/assets/139217939/15a85c8d-c769-4117-85c5-a7341a40f78c)

**Comment by dullbananas** [comment]
Still not fixed for me
